create table if not exists app_users (
  id bigint generated by default as identity primary key,
  name text,
  email text unique,
  password text,
  role text
);

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  service text not null,
  date text not null,
  time text not null,
  motorcycle text not null,
  description text,
  status text default 'Pendiente',
  client_name text,
  client_email text
);

insert into app_users (name, email, password, role)
values ('Administrador', 'admin@mono.com', '1234', 'admin');